namespace: preprod
volumeRessource:
  - name: wordpress-volume-pv
    namespace: preprod
    path: /var/www/html
    accessModes: ReadWriteMany
    capacity: 5Gi
    persistentVolumeClaim:
       accessModes: ReadWriteMany
       claimName: wordpress-volume-pvc
       capacity: 5Gi