{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aws-wordpress-php-fpm.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "aws-wordpress-php-fpm.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
